version: '3.9'

x-logging:    &default-logging
  driver:     "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    environment:
      NEXT_PUBLIC_NETWORK_NAME:               Symmchain
      NEXT_PUBLIC_NETWORK_SHORT_NAME:         Symmchain
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME:      Symmt
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL:    SYMMT
      NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS:  18
      # API
      NEXT_PUBLIC_API_PROTOCOL:               http # http | https
      NEXT_PUBLIC_API_HOST:                   localhost
      NEXT_PUBLIC_API_PORT:                   3001 # 443 if https
      NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL:     ws   # ws | wss
      # Assets
      NEXT_PUBLIC_APP_PROTOCOL:               http
      NEXT_PUBLIC_APP_HOST:                   localhost
      NEXT_PUBLIC_APP_PORT:                   3000 # 443 if https
      #
      # NEXT_PUBLIC_STATS_API_HOST:             http://localhost:3021/
      # NEXT_PUBLIC_VISUALIZE_API_HOST:         http://localhost:3031/
    ports:
      - "3000:3000"
    logging: *default-logging

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 6.10.1
    links:
      - db:database
    environment:
      CHAIN_ID:   391120
      COIN_NAME:  SYMMT
      PORT:       3010
      # RPC endpoint to fetch
      ETHEREUM_JSONRPC_HTTP_URL:  https://symmchain-node1.muon.net
      ETHEREUM_JSONRPC_TRACE_URL: https://symmchain-node1.muon.net
      # ETHEREUM_JSONRPC_HTTP_URLS:
    ports:
      - "3010:3010"
    logging: *default-logging

  # stats:
  #   depends_on:
  #     - stats-db
  #     - backend
  #   extends:
  #     file: ./services/stats.yml
  #     service: stats
  #   ports:
  #     - "3020:8050"
  #   logging: *default-logging

  # visualizer:
  #   extends:
  #     file: ./services/visualizer.yml
  #     service: visualizer
  #   ports:
  #     - "3030:8050"
  #   logging: *default-logging

  # stats-db:
  #   depends_on:
  #     stats-db-init:
  #       condition: service_completed_successfully
  #   extends:
  #     file: ./services/stats.yml
  #     service: stats-db
  #   logging: *default-logging

  # stats-db-init:
  #   extends:
  #     file: ./services/stats.yml
  #     service: stats-db-init
  #   logging: *default-logging

  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
    logging: *default-logging

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init
    logging: *default-logging

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
    logging: *default-logging

  sig-provider:
    extends:
      file: ./services/sig-provider.yml
      service: sig-provider
    logging: *default-logging

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    logging: *default-logging
